#ifndef TENSORFLOW_LITE_MICRO_VERSION_H_
#define TENSORFLOW_LITE_MICRO_VERSION_H_

#define TFLITE_MICRO_VERSION_MAJOR 2
#define TFLITE_MICRO_VERSION_MINOR 10
#define TFLITE_MICRO_VERSION_PATCH 0

#define TFLITE_MICRO_VERSION_STRING "2.10.0"

#endif  // TENSORFLOW_LITE_MICRO_VERSION_H_
